language: php

php:
  - 5.6

before_install:
  - composer selfupdate

install:
  - composer install --prefer-dist

before_script:
  - git config user.email "joshua.en@gmail.com"
  - git config user.name "trickeyone"

script: vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - vendor/bin/test-reporter
